name: CSV Update Workflow

on:
  push:
    branches:
      - main

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set permissions for Python script
      run: chmod +x wf_action_script/process_csv.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install frappe-client  # Install the Frappe client library

    - name: Read CSV and Post to ERPNext
      run: python wf_action_script/process_csv.py


